// Regenerates supabase/seed.sql from the JSON files in experiments/.
// The experiment JSON remains the single source of truth for the shared core;
// run this whenever an experiment is added or changed:
//
//   node scripts/gen-seed.mjs
//
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const expDir = join(root, "experiments");
const outFile = join(root, "supabase", "seed.sql");

const files = readdirSync(expDir).filter((f) => f.endsWith(".json")).sort();

const rows = files.map((file) => {
  const raw = readFileSync(join(expDir, file), "utf8");
  const exp = JSON.parse(raw);
  const stem = file.replace(/\.json$/, "");
  if (exp.id !== stem) {
    throw new Error(`id "${exp.id}" does not match filename "${stem}"`);
  }
  // Re-serialize compactly and escape single quotes for SQL.
  const jsonText = JSON.stringify(exp).replaceAll("'", "''");
  return `  ('${exp.id}', '${jsonText}'::jsonb)`;
});

const sql = `-- Generated by scripts/gen-seed.mjs — do not edit by hand.
-- Seeds the shared experiment library. Safe to re-run (upsert on id).

insert into public.experiments (id, data) values
${rows.join(",\n")}
on conflict (id) do update
  set data = excluded.data,
      updated_at = now();
`;

writeFileSync(outFile, sql, "utf8");
console.log(`Wrote ${outFile} with ${rows.length} experiment(s).`);
